import { Layout } from '@/_components/layout';
import type { Metadata } from 'next';
import poppins from './fontsConfig';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-secondary`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
